[project]
name = "images-to-video-conveter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddgs>=9.10.0",
    "moviepy>=2.2.1",
    "requests>=2.32.5",
]
